stages:
  - build
  - test
  - deploy

services:
  - docker:dind

backend_build:
  stage: build
  image: node:lts
  script:
    - cd backend
    - npm install
    - npm run build
  only:
    - master

backend_test:
  stage: test
  image: node:lts
  script:
    - cd backend
    # Bỏ npm test
  only:
    - master

backend_deploy:
  stage: deploy
  image: docker:20.10
  script:
    - cd backend
    - docker build -t ecommerce-be-node .
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - docker push ecommerce-be-node
  only:
    - master

frontend_build:
  stage: build
  image: node:lts
  script:
    - cd frontend
    - npm install
    - CI=false npm run build
  only:
    - master

frontend_test:
  stage: test
  image: node:lts
  script:
    - cd frontend
    # Bỏ npm test
  only:
    - master

frontend_deploy:
  stage: deploy
  image: docker:20.10
  script:
    - cd frontend
    - docker build -t ecommerce-fe .
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - docker push ecommerce-fe
  only:
    - master