services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: phantranxuanhuy/e-commerce-frontend:latest
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    networks:
      - app-network
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: phantranxuanhuy/e-commerce-backend:latest
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
    env_file:
      - ./backend/.env
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge